spring:

  datasource:
    url: jdbc:h2:file:../horizon-air/horizondb
    username: root
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
         show_sql: true
         format_sql: true
    hibernate.ddl-auto: update

  h2:
    console:
      enabled: true
      path: /h2
