spring:

 datasource:
   driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://${HOST}/${DATABASE}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
   username: ${USERNAME}
   password: ${PASSWORD}

 jpa:
     database: MYSQL
     database-platform: org.hibernate.dialect.MySQLDialect
     hibernate:
       ddl-auto: update
     show-sql: true


cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic

springdoc:
  swagger-ui:
   path: swagger-ui.html

